import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 40,
    padding: 16,
    position: 'relative',
    overflow: 'hidden',
  },
  headerText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: 'white',
    marginBottom: 50,
    textAlign: 'center',
    marginTop: 20,
    paddingLeft: 50,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 3,
    zIndex: 1,
    position: 'relative',
  },
  scrollView: {
    flex: 1,
    zIndex: 1,
  },
  cardContainer: {
    marginBottom: 20,
    borderRadius: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.25,
    shadowRadius: 5,
  },
  gradientCard: {
    padding: 20,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    overflow: 'hidden',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#1A237E',
    textShadowColor: 'rgba(255, 255, 255, 0.8)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 2,
    flexShrink: 1,
    flex: 1,
  },
  timeOfDay: {
    fontSize: 16,
    color: '#1A237E',
    fontWeight: '600',
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginLeft: 8,
  },
  warningText: {
    color: '#D32F2F',
    backgroundColor: 'rgba(255, 235, 238, 0.8)',
  },
  cardDescription: {
    fontSize: 16,
    color: '#333',
    fontWeight: '500',
    flex: 1,
    paddingRight: 70,
    lineHeight: 22,
  },
  descriptionWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 12,
    position: 'relative',
    minHeight: 50,
  },
  lottieWrapper: {
    position: 'absolute',
    right: -10,
    top: -10,
    width: 100,
    height: 100,
  },
  cardLottie: {
    width: '100%',
    height: '100%',
  },
  tipsContainer: {
    marginTop: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    padding: 12,
    borderRadius: 15,
  },
  tipsContent: {
    width: '100%',
  },
  tipText: {
    fontSize: 16,
    color: '#333',
    marginBottom: 8,
    fontWeight: '500',
    lineHeight: 22,
    paddingRight: 10,
  },
  languageToggle: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: 'center',
    marginBottom: 15,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  languageToggleText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  floatingAnimation: {
    position: 'absolute',
    width: 100,
    height: 100,
    zIndex: 0,
    opacity: 0.8,
  },
  animationContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    zIndex: 0,
    pointerEvents: 'none',
  },
});

export default styles; 